apiVersion: scheduling.run.ai/v2
kind: Queue
metadata:
    name: default-parent-queue
spec:
    resources:
        cpu:
            quota: -1
            limit: -1
            overQuotaWeight: 1
        gpu:
            quota: -1
            limit: -1
            overQuotaWeight: 1
        memory:
            quota: -1
            limit: -1
            overQuotaWeight: 1
---
apiVersion: scheduling.run.ai/v2
kind: Queue
metadata:
    name: default-queue
spec:
    parentQueue: default-parent-queue
    resources:
        cpu:
            quota: -1
            limit: -1
            overQuotaWeight: 1
        gpu:
            quota: -1
            limit: -1
            overQuotaWeight: 1
        memory:
            quota: -1
            limit: -1
            overQuotaWeight: 1
